remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "contrast" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
locale: "en-US"
title: "Kim-Anh Do Lab"
name: "Kim-Anh Do, Ph.D."
description: "Dr Kim-Anh Do's team website"
url: "https://kimanhdomda.github.io/"
repository: "kimanhdomda/COSMIC"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-seo-tag

github: 
  token: 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

head_scripts:
  - https://code.jquery.com/jquery-3.6.0.min.js

logo: "./assets/images/misc/logo.JPG"
masthead_title: ""

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      show_date: true

date_format: "%m-%d-%Y"

search: true
search_full_content: true
layout: search 
search_provider          : "lunr"

algolia:
  application_id         : "QB6HVGBSBA"
  index_name             : "dev_minimal-mistakes"
  search_only_api_key    : "9d5014e5bbc77372547bce778dfa5663"
  powered_by             : true

lunr:
  search_within_pages: true

og_image: "./assets/images/misc/logo.JPG"

social:
  type:  # Person or Organization (defaults to Person)
  name:  # If the user or organization name differs from the site's name
  links:
    - "https://www.linkedin.com/in/kim-anh-do-35b31463/"

author:
  name: "Kim-Anh Do, Ph.D."
  avatar: "https://raw.githubusercontent.com/KimAnhDoMDA/COSMIC/master/assets/images/people/KDoHeadshot.jpg"

  bio: "Pioneering Progress in Biostatistics and Cancer Research" # Note: Markdown is allowed
  
  links:
    - label: "Kim-Anh Do, Ph.D"
      icon: "https://faculty.mdanderson.org/profiles/kim-anh_do.html"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/kim-anh-do-35b31463/"
    - label: "KimDo@MDAnderson.org"
      icon: "fas fa-envelope"
      url: "mailto:kimdo@mdanderson.org"
    - label: "713-745-2483"
      icon: "fas fa-phone"
      url: "tel:713-745-2483"
    - label: "1515 Holcombe Blvd., Unit 1411"
      icon: "fas fa-map-marker-alt"
      url: "https://maps.app.goo.gl/meMJn75tevfSGZmc7"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single

defaults:
  # _foo
  - scope:
      path: ""
      type: foo
    values:
      layout: single

compress_html:
  clippings: all
  ignore:
    envs: development  # disable compression in dev environment

